---
slug: :backlight
depends:
  mikutter: 3.0.3
  plugin: []
version: '1.1'
author: toshi_a
name: Backlight
description: ノートPC等のディスプレイ/キーボードのバックライトの明るさを変更するmikutterコマンドを追加します。また、ふぁぼられる度に少しづつ画面が明るくなります。
